-- SQL para crear la tabla 'games' en Supabase
-- Copia y ejecuta este código en el SQL Editor de tu proyecto Supabase

CREATE TABLE games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  competition TEXT NOT NULL,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  home_score INTEGER,
  away_score INTEGER,
  period TEXT,
  status TEXT NOT NULL DEFAULT 'PROGRAMADO',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear índices para mejor rendimiento
CREATE INDEX idx_games_date ON games(date);
CREATE INDEX idx_games_status ON games(status);
CREATE INDEX idx_games_competition ON games(competition);

-- Insertar datos de ejemplo
INSERT INTO games (date, time, competition, home_team, away_team, home_score, away_score, period, status) VALUES
('2024-02-05', '18:00', 'Liga Nacional', 'Club Natación A', 'Club Natación B', 8, 6, '4T', 'FINALIZADO'),
('2024-02-05', '20:00', 'Liga Nacional', 'Club Natación C', 'Club Natación D', 5, 5, '3T', 'EN VIVO'),
('2024-02-06', '16:00', 'Copa del Rey', 'Club Natación E', 'Club Natación F', NULL, NULL, NULL, 'PROGRAMADO'),
('2024-02-06', '18:30', 'Liga Nacional', 'Club Natación G', 'Club Natación H', NULL, NULL, NULL, 'PROGRAMADO');

-- Configurar Row Level Security (RLS)
ALTER TABLE games ENABLE ROW LEVEL SECURITY;

-- Política para permitir lecturas públicas
CREATE POLICY "Enable read access for all users" ON games
  FOR SELECT USING (true);

-- Política para permitir inserciones (puedes ajustar esto según tus necesidades)
CREATE POLICY "Enable insert for authenticated users" ON games
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Política para permitir actualizaciones (puedes ajustar esto según tus necesidades)
CREATE POLICY "Enable update for authenticated users" ON games
  FOR UPDATE USING (auth.role() = 'authenticated');
